name: lstm-ecu-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - torch
    - yfinance
    - xgboost
    - pmdarima
    - shap
    - arch
    - ruptures
